### ISSUE TITLE
privileged operation issue

### ISSUE THREAD

**Issue by WeihanLi** [WeihanLi/dotnet-exec#11]
``` sh
dotnet-exec 'File.CreateSymbolicLink(@"C:\Users\weihan.li\.kube\config", @"C:\Users\weihan.li\.kube\paralus-nonprod.yaml")'
```

```
fail: dotnet-exec[0]
      Execute code exception
      System.IO.IOException: A required privilege is not held by the client. : 'C:\Users\weihan.li\.kube\config'
         at Interop.Kernel32.CreateSymbolicLink(String symlinkFileName, String targetFileName, Boolean isDirectory)
         at System.IO.File.CreateSymbolicLink(String path, String pathToTarget)
         at Submission#1.<<Initialize>>d__0.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
         at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
         at Microsoft.CodeAnalysis.Scripting.ScriptStateTaskExtensions.CastAsync[S,T](Task`1 task)
         at Exec.Services.CSharpScriptCompilerExecutor.Execute(CompileResult compileResult, ExecOptions options) in /_/src/dotnet-exec/Services/CSharpScriptingExecutor.cs:line 49
         at Exec.CommandHandler.Execute(ExecOptions options) in /_/src/dotnet-exec/CommandHandler.cs:line 92
```

**Comment by WeihanLi** [comment]
![image](https://github.com/WeihanLi/dotnet-exec/assets/7604648/e7bff687-e105-4a30-bfeb-cee8db83ed38)

**Comment by WeihanLi** [comment]
verified that it's the OS user permission issue, not related to the tool or .NET
![image](https://github.com/WeihanLi/dotnet-exec/assets/7604648/09dd8043-c340-4f07-92ab-2d47a05b4552)
